.gitignore, src/main/java/towssome/server/advice/ExceptionAdvice.java, src/main/java/towssome/server/controller/MemberController.java, src/main/java/towssome/server/dto/ErrorResult.java, src/main/java/towssome/server/dto/JoinReq.java, src/main/java/towssome/server/entity/Member.java, src/main/java/towssome/server/exception/DuplicateIdException.java, src/main/java/towssome/server/repository/MemberRepository.java, src/main/java/towssome/server/service/MemberService.java
회원가입 성공시 단순히 "Join Complete"라는 메세지를 보내도록 해 놨는데, 프론트와 협의해서 어떤 응답을 줘야할지 정해야 합니다. + 예외처리도
=> 회원가입 기능 작성

src/main/java/towssome/server/controller/ReviewController.java, src/main/java/towssome/server/dto/CursorResult.java, src/main/java/towssome/server/repository/ReviewPostRepository.java, src/main/java/towssome/server/service/ReviewPostService.java
사진 경로 삽입 구현 X
스크롤 -> 일단 review_id를 내림차순 정렬 후 글을 가져오는 것으로 구현
close #9
=> 리뷰 작성 / 스크롤 구현

src/main/java/towssome/server/advice/ExceptionAdvice.java, src/main/java/towssome/server/controller/CommentController.java, src/main/java/towssome/server/dto/CommentDTO.java, src/main/java/towssome/server/entity/Anniversary.java, src/main/java/towssome/server/entity/Comment.java, src/main/java/towssome/server/exception/NotFoundMemberException.java, src/main/java/towssome/server/exception/NotFoundReviewPostException.java, src/main/java/towssome/server/repository/CommentRepository.java, src/main/java/towssome/server/service/CommentService.java, src/main/resources/data.sql
Comment엔티티에 댓글 작성자 member_id가 없어서 추가했습니다
일단은 리뷰글 댓글 생성만 구현했는데,
리뷰글 자세히보기에서 댓글표출 할 때 무한스크롤로 할 지, 댓글 전체 리스트로 묶어서 보내줄지 몰라서 일단 냅뒀습니다.
#14
=> Comment에 member_id추가 & 리뷰글 댓글 작성

src/main/java/towssome/server/controller/CommunityController.java, src/main/java/towssome/server/controller/ReviewController.java, src/main/java/towssome/server/dto/CommunityPostRes.java, src/main/java/towssome/server/dto/CommunityPostSaveReq.java, src/main/java/towssome/server/dto/CommunityPostUpdateDto.java, src/main/java/towssome/server/dto/CommunityPostUpdateReq.java, src/main/java/towssome/server/dto/PhotoInPost.java, src/main/java/towssome/server/dto/UploadPhoto.java, src/main/java/towssome/server/entity/CommunityPost.java, src/main/java/towssome/server/exception/NotFoundCommunityPostException.java, src/main/java/towssome/server/exception/NotFoundPhotoException.java, src/main/java/towssome/server/repository/PhotoRepository.java, src/main/java/towssome/server/service/CommunityPostSaveDTO.java, src/main/java/towssome/server/service/CommunityService.java, src/main/java/towssome/server/service/MemberService.java, src/main/java/towssome/server/service/PhotoService.java, src/main/java/towssome/server/service/ReviewPostService.java
#18 
생성 / 조회 / 삭제 / 수정 구현
페이징 조회는 아직 페이지 구현 방식과 검색 방식이 애매해서 추후 구현 예정입니다
그리고 한글 주석이 깨지는 이유가 파일 인코딩 방식이 utf-8 이 아니라서 그런 것 같습니다
이 PR 에서는 x-windows-949 방식으로 인코딩된 파일들을 utf-8 방식으로 변경했습니다
=> 커뮤니티글 CURD

src/main/java/towssome/server/controller/ReviewController.java, src/main/java/towssome/server/dto/ReviewPostReq.java, src/main/java/towssome/server/dto/ReviewPostRes.java, src/main/java/towssome/server/dto/ReviewPostUpdateDto.java, src/main/java/towssome/server/dto/ReviewPostUpdateReq.java, src/main/java/towssome/server/entity/ReviewPost.java, src/main/java/towssome/server/repository/PhotoRepository.java, src/main/java/towssome/server/repository/ReviewPostRepository.java, src/main/java/towssome/server/service/PhotoService.java, src/main/java/towssome/server/service/ReviewPostService.java, src/main/resources/data.sql
reviewPost 컨트롤러에 CRUD 추가 구현
close #17
=> review CRUD

src/main/java/towssome/server/controller/ReviewController.java, src/main/java/towssome/server/controller/ViewlikeController.java, src/main/java/towssome/server/dto/ReviewPostReq.java, src/main/java/towssome/server/dto/ReviewPostRes.java, src/main/java/towssome/server/dto/ReviewPostUpdateReq.java, src/main/java/towssome/server/dto/ViewLikeReq.java, src/main/java/towssome/server/service/ReviewPostService.java, src/main/java/towssome/server/service/ViewlikeService.java
멤버마다 반환 값이 다른 함수들은 Security를 통해  getMember() 정보를 얻도록 수정
ReviewPost 엔티티에서 ReviewPostRes DTO를 반환하도록 수정
close #31
=> 함수에 Security 적용 및 반환 요소(Entity -> DTO) 수정

src/main/java/towssome/server/config/SecurityConfig.java, src/main/java/towssome/server/controller/BookMarkController.java, src/main/java/towssome/server/controller/CategoryController.java, src/main/java/towssome/server/controller/CommunityController.java, src/main/java/towssome/server/controller/MemberController.java, src/main/java/towssome/server/controller/ProfileController.java, src/main/java/towssome/server/controller/ReviewController.java, src/main/java/towssome/server/dto/BookmarkReq.java, src/main/java/towssome/server/dto/CategoryRes_.java, src/main/java/towssome/server/dto/CreateCategoryReq.java, src/main/java/towssome/server/dto/DeleteCategoryReq.java, src/main/java/towssome/server/dto/ProfileRes.java, src/main/java/towssome/server/dto/UpdateProfileReq.java, src/main/java/towssome/server/entity/BookMark.java, src/main/java/towssome/server/entity/Member.java, src/main/java/towssome/server/entity/Photo.java, src/main/java/towssome/server/enumrated/PhotoType.java, src/main/java/towssome/server/jwt/JoinService.java, src/main/java/towssome/server/jwt/JwtFilter.java, src/main/java/towssome/server/repository/BookMarkRepository.java, src/main/java/towssome/server/service/BookMarkService.java, src/main/java/towssome/server/service/MemberService.java, src/main/java/towssome/server/service/PhotoService.java, src/main/java/towssome/server/service/SubscribeService.java, src/main/java/towssome/server/service/ViewlikeService.java
#26 
프로필을 불러올 때 전부 불러오는 방식 대신 개별로 따로 조회하는 방식을 채용했습니다.
북마크를 조회할 때는 카테고리를 통해 조회할 수 있습니다.
북마크는 무한스크롤 방식으로 페이징 되었습니다.
Member 엔티티의 변경이 있습니다.
Stirng profilePhotoPath -> Photo profilePhoto로 수정되었습니다.
이에 따라 머지 후 각자의 테스트 데이터나 테스트에 변경이 필요할 수 있습니다.
=> 북마크 , 카테고리 조회 + 프로필 조회 및 업데이트 기능 추가

src/main/java/towssome/server/controller/CommunityController.java, src/main/java/towssome/server/dto/CommunitySearchCondition.java, src/main/java/towssome/server/entity/CommunityPost.java, src/main/java/towssome/server/entity/Vote.java, src/main/java/towssome/server/repository/CommunityPostRepositoryImpl.java, src/main/java/towssome/server/service/CommunityService.java, src/main/java/towssome/server/service/PhotoService.java, src/main/java/towssome/server/service/VoteService.java
#39 
CommunityPost 본문 검색 기능을 추가하였습니다.
이와 별개로, 커뮤니티글 -> 투표 -> 투표 요소 -> 투표 요소 사진으로 구성되어 있었는데, 기존에는 사진이 삭제되지 않는 버그가 있었지만 커뮤니티글을 삭제하면 이 모두가 동시에 삭제되도록 수정하였습니다.
=> 커뮤니티 본문 검색 기능 외 버그 수정

src/main/java/towssome/server/controller/CommunityController.java, src/main/java/towssome/server/controller/VoteController.java, src/main/java/towssome/server/dto/CommunityPostRes.java, src/main/java/towssome/server/dto/CommunityPostSaveDTO.java, src/main/java/towssome/server/dto/CommunityPostSaveReq.java, src/main/java/towssome/server/dto/CreatedPostRes.java, src/main/java/towssome/server/dto/VoteAttributeReq.java, src/main/java/towssome/server/entity/CommunityPost.java, src/main/java/towssome/server/service/CommunityService.java, src/main/java/towssome/server/service/VoteService.java
#41 
커뮤니티글 익명 전환 기능 + 커뮤니티글 생성 로직을 변경하였습니다
CommunityPost 에 Boolean isAnonymous 속성이 추가되었습니다
투표 추가/ 취소 기능이 추가되었습니다
=> 커뮤니티글 익명 전환 기능 및 투표 기능

src/main/java/towssome/server/controller/BookMarkController.java, src/main/java/towssome/server/controller/ReviewController.java, src/main/java/towssome/server/controller/ViewlikeController.java, src/main/java/towssome/server/dto/CursorResult.java, src/main/java/towssome/server/dto/ReviewListRes.java, src/main/java/towssome/server/python/hashtagmaker.py, src/main/java/towssome/server/repository/ReviewPostRepositoryCustom.java, src/main/java/towssome/server/repository/ReviewPostRepositoryImpl.java, src/main/java/towssome/server/repository/ViewLikeRepositoryCustom.java, src/main/java/towssome/server/repository/ViewLikeRepositoryImpl.java, src/main/java/towssome/server/service/ReviewPostService.java, src/main/java/towssome/server/service/SubscribeService.java, src/main/java/towssome/server/service/ViewlikeService.java
Query -> Query dsl로 변경
내가 작성한 review 글, 좋아요나 최근 조회한 글에는 정렬 기능 추가
CursorResult에 cursorId까지 전달하도록 변경
close #56
=> 무한스크롤 추가 구현

.gitignore, src/main/java/towssome/server/advice/ExceptionAdvice.java, src/main/java/towssome/server/config/SecurityConfig.java, src/main/java/towssome/server/controller/HashtagController.java, src/main/java/towssome/server/controller/MatingController.java, src/main/java/towssome/server/controller/MemberController.java, src/main/java/towssome/server/controller/ProfileController.java, src/main/java/towssome/server/dto/CreateMateRes.java, src/main/java/towssome/server/dto/CreateVirtualRes.java, src/main/java/towssome/server/dto/HashtagRes.java, src/main/java/towssome/server/dto/MatingRes.java, src/main/java/towssome/server/dto/ProfileRes.java, src/main/java/towssome/server/entity/Mating.java, src/main/java/towssome/server/entity/ProfileTag.java, src/main/java/towssome/server/entity/VirtualMateHashtag.java, src/main/java/towssome/server/enumrated/MatingStatus.java, src/main/java/towssome/server/exception/AlreadyExistMatingException.java, src/main/java/towssome/server/exception/NotFoundMatingException.java, src/main/java/towssome/server/jwt/JoinDTO.java, src/main/java/towssome/server/jwt/JoinService.java, src/main/java/towssome/server/python/hashtagmaker.py, src/main/java/towssome/server/repository/HashTagRepository.java, src/main/java/towssome/server/repository/MatingRepository.java, src/main/java/towssome/server/repository/ProfileTagRepository.java, src/main/java/towssome/server/repository/SubscribeRepositoryImpl.java, src/main/java/towssome/server/repository/VirtualMateHashtagRepository.java, src/main/java/towssome/server/service/MatingService.java, src/main/java/towssome/server/service/MemberService.java
#55 
위 기능을 추가하였습니다
추가로, 회원만 사용가능한 URL 일부를 시큐리티 설정에 추가하였습니다
=> 메이팅/프로필태그/연인프로필/가상연인프로필 기능 추가

.gitignore, src/main/java/towssome/server/advice/ExceptionAdvice.java, src/main/java/towssome/server/config/SecurityConfig.java, src/main/java/towssome/server/controller/ReplyController.java, src/main/java/towssome/server/dto/CreateReplyReq.java, src/main/java/towssome/server/dto/CreateRes.java, src/main/java/towssome/server/dto/ReplyRes.java, src/main/java/towssome/server/dto/UpdateReplyReq.java, src/main/java/towssome/server/entity/Reply.java, src/main/java/towssome/server/exception/NotFoundReplyException.java, src/main/java/towssome/server/exception/PageException.java, src/main/java/towssome/server/repository/ReplyRepository.java, src/main/java/towssome/server/service/PhotoService.java, src/main/java/towssome/server/service/ReplyService.java
답변글 CRUD + 답변글 채택 기능을 추가하였습니다
답변글 좋아요 기능은 추후에 추가하겠습니다
=> 답변글 CRUD 추가

src/main/java/towssome/server/controller/ProfileController.java, src/main/java/towssome/server/controller/ReviewController.java, src/main/java/towssome/server/dto/ReviewSimpleRes.java, src/main/java/towssome/server/entity/ReviewPost.java, src/main/java/towssome/server/service/ReviewPostService.java
ReviewSimpleRes로 간단한 정보만 전송
review/my -> profile/review
close #65
=> ReviewSimpleRes로 간단한 정보만 전송

src/main/java/towssome/server/dto/ReviewSimpleRes.java, src/main/java/towssome/server/entity/Category.java, src/main/java/towssome/server/entity/CommunityPost.java, src/main/java/towssome/server/entity/HashtagClassification.java, src/main/java/towssome/server/service/ReviewPostService.java
리뷰글 리스트 dto 에 id 타입 추가
일부 엔티티 id 생성 타입 identity로 수정
=> 리뷰글 리스트 dto 수정 + id 생성 타입 수정

src/main/java/towssome/server/config/CorsConfig.java, src/main/java/towssome/server/controller/BookMarkController.java, src/main/java/towssome/server/controller/CategoryController.java, src/main/java/towssome/server/controller/CommentController.java, src/main/java/towssome/server/controller/HashtagController.java, src/main/java/towssome/server/controller/MemberController.java, src/main/java/towssome/server/controller/ProfileController.java, src/main/java/towssome/server/controller/RankController.java, src/main/java/towssome/server/controller/ReviewController.java, src/main/java/towssome/server/controller/SubscribeController.java, src/main/java/towssome/server/controller/ViewlikeController.java, src/main/java/towssome/server/dto/CommentReq.java, src/main/java/towssome/server/dto/PageResult.java, src/main/java/towssome/server/dto/ReviewPostReq.java, src/main/java/towssome/server/dto/ReviewPostUpdateReq.java, src/main/java/towssome/server/entity/Comment.java, src/main/java/towssome/server/entity/CommunityPost.java, src/main/java/towssome/server/entity/ReviewPost.java, src/main/java/towssome/server/jwt/JoinService.java, src/main/java/towssome/server/repository/HashTagRepository.java, src/main/java/towssome/server/repository/HashTagRepositoryCustom.java, src/main/java/towssome/server/repository/HashTagRepositoryImpl.java, src/main/java/towssome/server/service/CommentService.java, src/main/java/towssome/server/service/HashtagClassificationService.java, src/main/java/towssome/server/service/HashtagService.java, src/main/java/towssome/server/service/ReviewPostService.java, src/main/java/towssome/server/service/SubscribeService.java
=> Swagger API 설명 추가

src/main/java/towssome/server/advice/ExceptionAdvice.java, src/main/java/towssome/server/advice/UtilScheduler.java, src/main/java/towssome/server/config/EmailConfig.java, src/main/java/towssome/server/controller/MemberController.java, src/main/java/towssome/server/dto/EmailCheckReq.java, src/main/java/towssome/server/dto/EmailReq.java, src/main/java/towssome/server/entity/EmailVerification.java, src/main/java/towssome/server/exception/EmailSendException.java, src/main/java/towssome/server/exception/ExpirationEmailException.java, src/main/java/towssome/server/jwt/JoinService.java, src/main/java/towssome/server/repository/EmailVerificationRepository.java, src/main/java/towssome/server/service/MailSendService.java
#78 
build.gradle 에 다음 의존성을 추가해주세요 !!
implementation group: 'org.springframework.boot', name: 'spring-boot-starter-mail', version: '2.6.3'
implementation 'javax.mail:mail:1.4.7'
implementation 'org.springframework:spring-context-support:5.3.9'
이메일 인증 기능을 구현하였습니다
인증번호는 6자리 정수입니다
개발 환경에서는 이메일 인증을 안받으셔도 됩니다
=> 이메일 인증 기능 구현

src/main/java/towssome/server/config/SecurityConfig.java, src/main/java/towssome/server/python/hashtagmaker.py
좀 더 해시태그가 잘(?) 추출될 수 있도록 했습니다.
=> 해시태그 추출 수정

src/main/java/towssome/server/controller/HashtagController.java, src/main/java/towssome/server/controller/ProfileController.java, src/main/java/towssome/server/controller/ViewlikeController.java, src/main/java/towssome/server/dto/CursorResult.java, src/main/java/towssome/server/entity/ViewLike.java, src/main/java/towssome/server/repository/ViewLikeRepository.java, src/main/java/towssome/server/repository/ViewLikeRepositoryCustom.java, src/main/java/towssome/server/repository/ViewLikeRepositoryImpl.java, src/main/java/towssome/server/service/ViewlikeService.java
시간으로 정렬해서 무한스크롤 되도록 바꿨습니다.
페이지는 1 페이지부터 시작, 페이지 번호가 없으면 자동으로 1페이지부터
close #92
=> 최근 조회, 좋아요 무한 스크롤 개선

src/main/java/towssome/server/advice/MemberAdvice.java, src/main/java/towssome/server/controller/HashtagController.java, src/main/java/towssome/server/controller/ProfileController.java, src/main/java/towssome/server/dto/CreateVirtualRes.java, src/main/java/towssome/server/dto/ReviewPostReq.java, src/main/java/towssome/server/dto/UpdateProfileReq.java, src/main/java/towssome/server/dto/VirtualRes.java, src/main/java/towssome/server/entity/Member.java, src/main/java/towssome/server/enumrated/PhotoType.java, src/main/java/towssome/server/repository/ProfileTagRepository.java, src/main/java/towssome/server/service/MemberService.java, src/main/java/towssome/server/service/PhotoService.java, src/main/java/towssome/server/service/ReviewPostService.java
=> 가상 연인 프로필 사진, 이름 추가 + 리뷰글 생성시 starPoint 삭제 + 프로필 태그 수정 기능

src/main/java/towssome/server/controller/CommentController.java, src/main/java/towssome/server/service/CommentService.java
프런트에서 댓글 생성될 때 commentId도 응답되게 해달라고 해서 수정했습니다.
=> 댓글 생성 시 commentId 응답 추가

src/main/java/towssome/server/config/CorsConfig.java, src/main/java/towssome/server/config/SecurityConfig.java, src/main/java/towssome/server/controller/MemberController.java, src/main/java/towssome/server/dto/IdDupCheckReq.java, src/main/java/towssome/server/entity/Member.java, src/main/java/towssome/server/jwt/JoinDTO.java, src/main/java/towssome/server/jwt/JwtFilter.java, src/main/java/towssome/server/repository/MemberRepository.java, src/main/java/towssome/server/service/JoinService.java, src/main/java/towssome/server/service/MemberService.java
CORS 설정과 회원가입 시 인증 로직을 변경하였습니다
이제 아이디와 이메일 모두 중복체크를 해야 합니다
=> CORS 설정 + 회원가입 시 아이디, 이메일 중복체크

src/main/java/towssome/server/oauth2/CustomSuccessHandler.java
현재 로컬 환경에서만 소셜 로그인이 진행되도록 수정하였습니다. (네이버 인증서버 이슈)
추후에 개발이 완료되면 배포된 리액트 서버에서 되도록 수정하겠습니다
=> 하나의 환경에서만 소셜 로그인 되도록 설정

src/main/java/towssome/server/oauth2/CustomOAuth2UserService.java, src/main/java/towssome/server/oauth2/CustomSuccessHandler.java, src/main/java/towssome/server/repository/MemberRepository.java
이 PR이 머지되면 
`social.user = login`
을 application.porperties에 추가해주세요
=> 소셜 로그인 url 수정

src/main/java/towssome/server/controller/CategoryController.java, src/main/java/towssome/server/controller/CommunityController.java, src/main/java/towssome/server/controller/MatingController.java, src/main/java/towssome/server/controller/ReplyController.java, src/main/java/towssome/server/controller/VoteController.java, src/main/java/towssome/server/dto/MatingIdReq.java, src/main/java/towssome/server/dto/MatingRes.java, src/main/java/towssome/server/dto/MemberNameReq.java, src/main/java/towssome/server/entity/ReviewPost.java, src/main/java/towssome/server/service/JoinService.java
사용되지 않는 컨트롤러들을 일단 삭제하지 않고 Deprecated 설명만 달아 두었습니다. (후에 다시 쓸 수도 있으니까...)
회원가입 시 profileTag가 없으면 exception이 발생하던 문제를 해결했습니다
=> 스웨거 desc 추가 및 버그 수정

src/main/java/towssome/server/advice/ServiceAdvice.java, src/main/java/towssome/server/advice/UtilScheduler.java, src/main/java/towssome/server/controller/CalendarController.java, src/main/java/towssome/server/controller/CommunityController.java, src/main/java/towssome/server/controller/HashtagController.java, src/main/java/towssome/server/controller/OAuthController.java, src/main/java/towssome/server/controller/QuickRecommendController.java, src/main/java/towssome/server/controller/ReplyController.java, src/main/java/towssome/server/controller/VoteController.java, src/main/java/towssome/server/dto/HashtagDeleteReq.java, src/main/java/towssome/server/dto/OAuthInitialConfigReq.java, src/main/java/towssome/server/jwt/ReissueController.java, src/main/java/towssome/server/service/JoinService.java, src/main/java/towssome/server/service/MemberService.java, src/main/java/towssome/server/service/PhotoService.java
서비스 레이어간 순환참조 문제 발생 가능성으로 코드 리팩토링을 진행하였습니다
=> 스웨거 추가 및 코드 리팩토링

src/main/java/towssome/server/entity/Member.java
소셜 로그인 초기화 시 ROLE이 제대로 수정되지 않던 문제를 수정했습니다
=> 소셜 로그인 계정 초기화 수정

src/main/java/towssome/server/controller/OAuthController.java, src/main/java/towssome/server/entity/Member.java, src/main/java/towssome/server/enumrated/SocialType.java, src/main/java/towssome/server/oauth2/CustomOAuth2UserService.java, src/main/java/towssome/server/oauth2/KakaoRes.java
#117 
카카오 소셜 로그인을 완성했습니다. 이 PR이 머지되면
application.properties에 다음 설정을 추가해주세요
```
#registration kakao
spring.security.oauth2.client.registration.kakao.client-name=kakao
spring.security.oauth2.client.registration.kakao.client-id=2b07fff90cd4bec9bc3fed6fc0855390
spring.security.oauth2.client.registration.kakao.client-secret=niMLhZTVrSp9kEcdwXg0iNcnOyEJz5NY
spring.security.oauth2.client.registration.kakao.scope= account_email, profile_nickname
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8080/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post …
```
=> 카카오 소셜 로그인 완성

src/main/java/towssome/server/controller/ProfileTagController.java, src/main/java/towssome/server/controller/RecommendController.java, src/main/java/towssome/server/dto/AllMemberProfileTagRes.java, src/main/java/towssome/server/entity/Cluster.java, src/main/java/towssome/server/python/hashtagmaker.py, src/main/java/towssome/server/python/userClustering.py, src/main/java/towssome/server/repository/ClusterRepository.java, src/main/java/towssome/server/service/ClusterService.java, src/main/java/towssome/server/service/ProfileTagService.java, src/main/java/towssome/server/service/RecommendService.java
사용자 태그 유사도에 따라 클러스터링 완성했습니다
유사도는 FastWord, 클러스터링은 K-Means 사용했습니다.
같은 클러스터링에 포함된 계정 추천 목록 또한 완성했습니다.
=> 클러스터링, 계정 추천

src/main/java/towssome/server/controller/CommentController.java, src/main/java/towssome/server/dto/ChangeLikeRes.java, src/main/java/towssome/server/entity/CommentLike.java, src/main/java/towssome/server/service/CommentLikeService.java
좋아요 누를때 현재 좋아요 상태 응답으로 추가해달라고해서 수정합니다
=> 댓글 좋아요 Res추가

.gitattributes, src/main/java/towssome/server/python/hashtagmaker.py, src/main/java/towssome/server/python/model.pt
모델 용량이 커서 Git LFS를 통해 올립니다.
아래는 Git LFS 사용 방법입니다.
1. Git LFS 설치
macOS: brew install git-lfs
Windows: [Git LFS 다운로드](https://git-lfs.github.com/) 후 설치.
2. Git LFS 초기화
Git LFS 설치 후, 각 팀원이 자신의 로컬 Git 저장소에서 Git LFS를 초기화. 이는 팀원별로 한 실행
git lfs install
3. Git Pull
대용량 파일과 .gitattributes 파일을 받아오기 위해 최신 커밋을 풀(Pull)
Git LFS가 설치되어 있으면, 대용량 파일이 자동으로 Git LFS 서버에서 다운로드 됩니다.
AWS 서버에서도 Git LFS를 사용해 대용량 파일을 처리하려면 Git LFS를 설치하고 설정해야 합니다. 
1. Git LFS 설치
AWS EC2 인스턴스와 같은 서버 환경에서 Git LFS를 설치해야 합니다. 
sudo apt-get install git-lfs
2. Git LFS 초기화
Git LFS 설치 후, 저장소에서 Git LFS를 활성화해야 합니다.
git lfs install
3. Git Pull
그 다음, 서버에서 프로젝트의 최신 상태를 받아와야 합니다.
=> 명사 추출 모델 추가

src/main/java/towssome/server/dto/ReviewPostReq.java, src/main/java/towssome/server/dto/ReviewPostRes.java, src/main/java/towssome/server/entity/ReviewPost.java, src/main/java/towssome/server/python/hashtagmaker.py, src/main/java/towssome/server/service/ReviewPostService.java
리뷰글 item(품목) 열 추가 및 item으로 네이버 쇼핑몰 url get
close #125
=> 리뷰글 item(품목) 열 추가 및 item으로 네이버 쇼핑몰 url get

src/main/java/towssome/server/service/CommentLikeService.java, src/main/java/towssome/server/service/CommentService.java
=> 댓글 member null일 때 예외처리

src/main/java/towssome/server/advice/MailSendAdvice.java, src/main/java/towssome/server/controller/MemberController.java, src/main/java/towssome/server/dto/EmailAuthNumReq.java, src/main/java/towssome/server/dto/EmailUsernameReq.java, src/main/java/towssome/server/dto/PasswordReq.java, src/main/java/towssome/server/dto/UsernameRes.java, src/main/java/towssome/server/entity/EmailVerification.java, src/main/java/towssome/server/enumrated/EmailType.java, src/main/java/towssome/server/repository/EmailVerificationRepository.java, src/main/java/towssome/server/repository/member/MemberRepositoryCustom.java, src/main/java/towssome/server/repository/member/MemberRepositoryImpl.java, src/main/java/towssome/server/service/JoinService.java, src/main/java/towssome/server/service/MemberService.java, src/main/java/towssome/server/service/ReviewPostService.java
#129 
- 이메일로 해당 회원의 아이디를 찾을 수 있습니다 (/memeber/findId)
- 이메일과 아이디가 일치하면 해당 아이디로 비밀번호 재설정 인증번호를 받을 수 있습니다 (/member/reconfig_password/req)
- 비밀번호 재설정 인증번호 일치 여부를 api로 알 수 있습니다 (/member/reconfig_password/authenticate)
=> 개인정보 찾기 기능 추가

src/main/java/towssome/server/controller/CommentController.java, src/main/java/towssome/server/dto/CommentRes.java, src/main/java/towssome/server/dto/ProfileSimpleRes.java, src/main/java/towssome/server/service/CommentService.java
댓글 Response에 프로필 사진, 닉네임이 없었어서 추가했습니다!
=> 댓글 프로필 정보 추가

src/main/java/towssome/server/controller/HashtagController.java, src/main/java/towssome/server/controller/RecommendController.java, src/main/java/towssome/server/dto/ListResultRes.java, src/main/java/towssome/server/dto/QuickRecommendReq.java, src/main/java/towssome/server/python/hashtagmaker.py, src/main/java/towssome/server/python/tagRecommend.py, src/main/java/towssome/server/python/userClustering.py, src/main/java/towssome/server/repository/hashtag/HashTagRepositoryCustom.java, src/main/java/towssome/server/repository/hashtag/HashTagRepositoryImpl.java, src/main/java/towssome/server/repository/hashtag_classification/HashtagClassificationRepositoryCustom.java, src/main/java/towssome/server/repository/hashtag_classification/HashtagClassificationRepositoryImpl.java, src/main/java/towssome/server/repository/viewlike/ViewLikeRepositoryCustom.java, src/main/java/towssome/server/repository/viewlike/ViewLikeRepositoryImpl.java, src/main/java/towssome/server/service/HashtagService.java, src/main/java/towssome/server/service/RecommendService.java
검색 결과 없을 시 추천 태그 구현했습니다.
사용자가 조회한 리뷰글의 태그와 비슷한 리뷰글 태그 + 검색 키워드와 유사한 태그를 수합해서 추천합니다.
=> 검색 결과 없을 시 추천 태그

src/main/java/towssome/server/jwt/JwtUtil.java, src/main/java/towssome/server/jwt/LoginFilter.java
필터 내에서 트랜잭션이 걸리지 않음으로 인해 addRefreshToken 메소드의 RT 삭제 기능이 작동되지 않아서 로그인이 정상적으로 되지 않던 문제 수정
=> fix(Login): 로그인 시 트랜잭션 문제 수정

.github/workflows/jib-build.yaml, .gitignore, build.gradle, src/main/resources/application-prod.properties
=> feat(CICD): cicd 기능 추가

.github/workflows/jib-build.yaml
시간을 한국으로 설정하고 IP를 host와 연결되도록 명령어 설정
=> fix(action): 명령어 수정

src/main/java/towssome/server/controller/HashtagController.java, src/main/java/towssome/server/controller/RecommendController.java, src/main/java/towssome/server/dto/ProfileRes_.java, src/main/java/towssome/server/dto/RecommendTagRes.java, src/main/java/towssome/server/python/hashtagmaker.py, src/main/java/towssome/server/python/tagRecommend.py, src/main/java/towssome/server/repository/cluster/ClusterRepository.java, src/main/java/towssome/server/repository/cluster/ClusterRepositoryCustom.java, src/main/java/towssome/server/repository/cluster/ClusterRepositoryImpl.java, src/main/java/towssome/server/repository/hashtag/HashTagRepositoryImpl.java, src/main/java/towssome/server/repository/member/MemberRepository.java, src/main/java/towssome/server/repository/member/MemberRepositoryCustom.java, src/main/java/towssome/server/service/RecommendService.java
검색바 하단의 검색어(해시태그) 추천 기능 추가하고
검색 결과 없을 시 검색어 추천 기능 수정했습니다!
그리고 프로필 팔로우 페이지 수정했습니다!
=> 검색 시 검색어(해시태그) 추천 수정 & 프로필 팔로우 추천 수정

src/main/java/towssome/server/controller/CommunityController.java, src/main/java/towssome/server/controller/ReplyController.java, src/main/java/towssome/server/controller/ReviewController.java, src/main/java/towssome/server/controller/VoteController.java, src/main/java/towssome/server/service/ReviewPostService.java
=> fix(Review): 구독 리뷰글

src/main/resources/application-prod.properties
=> fix(application_properites): 설정 파일 수정

src/main/java/towssome/server/controller/CommentController.java, src/main/java/towssome/server/dto/EmptyRes.java
=> fix(Comment): 고정댓글 수정

src/main/java/towssome/server/controller/ProfileController.java, src/main/java/towssome/server/dto/ProfileRes.java
프로필 조회 시 프로필 username 반환하도록 수정
=> fix(Profile): 프로필 조회 수정

src/main/java/towssome/server/controller/OAuthController.java, src/main/java/towssome/server/dto/AccessRefreshRes.java, src/main/java/towssome/server/dto/SocialLoginSuccessRes.java
=> feat(OAuth): 소셜 로그인 성공 응답 수정

src/main/java/towssome/server/controller/OAuthController.java, src/main/java/towssome/server/oauth2/CustomSuccessHandler.java
=> feat(OAuth): 소셜 로그인 수정

src/main/java/towssome/server/service/ReviewPostService.java
=> fix(Review): 생성 수정

src/main/java/towssome/server/entity/CalendarPersonalSchedule.java, src/main/java/towssome/server/entity/CalendarPost.java, src/main/java/towssome/server/entity/CalendarPostComment.java, src/main/java/towssome/server/entity/CalendarSchedule.java, src/main/java/towssome/server/entity/CalendarTag.java, src/main/java/towssome/server/entity/Photo.java
캘린더 태그, 개인 일정 태그, 캘린더 일정, 캘린더 게시글, 캘린더 코멘트 추가 및 photo 엔티티에 캘린더 일정 관계 추가
=> feat(Calendar): 엔티티 추가

.github/workflows/jib-build.yaml, build.gradle, src/main/java/towssome/server/repository/CalendarPersonalScheduleRepository.java, src/main/java/towssome/server/repository/CalendarTagRepository.java
github secret으로 수정할 수 있도록 은닉 후 환경변수로 받아오도록 수정
=> build.gradel에서 jib build명 은닉

README.md, src/main/java/towssome/server/dto/CCPCDTO.java, src/main/java/towssome/server/dto/CalendarInfoByMonthDTO.java, src/main/java/towssome/server/dto/CalendarPostDetailInfo.java, src/main/java/towssome/server/dto/CalendarScheduleDetailInfo.java, src/main/java/towssome/server/dto/CalendarScheduleInfo.java, src/main/java/towssome/server/dto/CalendarTagInfo.java, src/main/java/towssome/server/dto/CreateCalendarPostDTO.java, src/main/java/towssome/server/dto/CreateCalendarTagDTO.java, src/main/java/towssome/server/dto/SearchPoomPoomLogDTO.java, src/main/java/towssome/server/dto/SearchPoomPoomLogInfo.java, src/main/java/towssome/server/dto/UpdateCalendarPostDTO.java, src/main/java/towssome/server/dto/UpdateCalendarTagDTO.java, src/main/java/towssome/server/dto/updateCPCDTO.java, src/main/java/towssome/server/service/CalendarService.java, src/main/java/towssome/server/service/CalendarServiceInterface.java
=> 캘린더 서비스 인터페이스 작성

src/main/java/towssome/server/advice/ServiceAdvice.java, src/main/java/towssome/server/controller/CalendarController.java, src/main/java/towssome/server/dto/CalendarTagInfo.java, src/main/java/towssome/server/dto/CreateCalendarTagDTO.java, src/main/java/towssome/server/dto/CreateCalendarTagReq.java, src/main/java/towssome/server/dto/UpdateCalendarTagReq.java, src/main/java/towssome/server/entity/CalendarTag.java, src/main/java/towssome/server/service/CalendarService.java, src/main/java/towssome/server/service/CalendarServiceInterface.java
=> feat(CalendarTag): 캘린더 태그 CRUD 기능 완성

.github/workflows/server-restart.yaml
이제 이 리포지토리에서 수동으로 서버 재시작이 가능합니다!
=> 서버 재시작 workflow 추가

src/main/java/towssome/server/advice/PhotoAdvice.java, src/main/java/towssome/server/controller/CalendarController.java, src/main/java/towssome/server/dto/CalendarScheduleDetailInfo.java, src/main/java/towssome/server/dto/CreateCalendarScheduleDTO.java, src/main/java/towssome/server/dto/CreateCalendarScheduleReq.java, src/main/java/towssome/server/dto/PostInSchedule.java, src/main/java/towssome/server/dto/UpdateCalendarScheduleDTO.java, src/main/java/towssome/server/dto/UpdateCalendarScheduleReq.java, src/main/java/towssome/server/entity/CalendarSchedule.java, src/main/java/towssome/server/repository/CalendarPostRepository.java, src/main/java/towssome/server/service/CalendarService.java, src/main/java/towssome/server/service/CalendarServiceInterface.java
=> feat(CalendarSchedule): 캘린더 일정 CRUD 완성

src/main/java/towssome/server/dto/CPCRes.java, src/main/java/towssome/server/entity/CalendarPostComment.java, src/main/java/towssome/server/service/CalendarService.java
=> 게시글 코멘트에 baseentity 상속

src/main/java/towssome/server/controller/CalendarController.java, src/main/java/towssome/server/dto/CalendarInfoByMonthDTO.java, src/main/java/towssome/server/dto/CalendarScheduleInfo.java, src/main/java/towssome/server/dto/MemberInfo.java, src/main/java/towssome/server/entity/CalendarTag.java, src/main/java/towssome/server/repository/CalendarScheduleRepository.java, src/main/java/towssome/server/service/CalendarService.java
=> feat(Calenar): 캘린더 월별 일정 조회 기능

src/main/java/towssome/server/jwt/CustomAuthenticationEntryPoint.java
=> feat(CustomAuthenticationEntryPoint): 응답 인코딩 수정

src/main/java/towssome/server/entity/CalendarPost.java, src/main/java/towssome/server/enumrated/PostType.java, src/main/java/towssome/server/service/CalendarService.java
=> fix(CalendarPost): 게시글 타입 추가

src/main/java/towssome/server/repository/MatingRepository.java, src/main/java/towssome/server/service/MatingService.java
=> 연인 연동 예외 처리 추가

src/main/java/towssome/server/advice/ExceptionAdvice.java, src/main/java/towssome/server/controller/CalendarController.java, src/main/java/towssome/server/dto/PoomPoomLogInfo.java, src/main/java/towssome/server/dto/SearchPoomPoomLogDTO.java, src/main/java/towssome/server/dto/SearchPoomPoomLogInfo.java, src/main/java/towssome/server/exception/InvalidMonthException.java, src/main/java/towssome/server/repository/calendar_post/CalendarPostRepository.java, src/main/java/towssome/server/repository/calendar_post/CalendarPostRepositoryCustom.java, src/main/java/towssome/server/repository/calendar_post/CalendarPostRepositoryImpl.java, src/main/java/towssome/server/service/CalendarService.java, src/main/java/towssome/server/service/CalendarServiceInterface.java
=> 사이드바 품품로그 & 월별 품품로그
